spring:
  datasource:
    driver-class-name: com.kingbase8.Driver
    url: jdbc:kingbase8://localhost:54321/student_db
    username: system
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启 SQL 日志，方便观察验证
    map-underline-to-camel-case: true # ????????

# ========== 自定义加密配置 ==========
app:
  security:
    aes-key: ruc2026secretkey!            # AES 密钥（必须 16 字节，生产环境请使用更复杂的值）